import { RESOURCE_CODES, type ResourceCode } from "@/lib/access-control/resources";

export const accessProfileSeedCatalog = [
  {
    code: "OWNER",
    description: "Perfil interno da assinatura principal do sistema.",
    isAdministrator: true,
    isSystem: true,
    level: "OWNER",
    name: "Owner",
    sequenceNumber: 0,
    status: "ACTIVE",
    tier: "ADMINISTRATOR",
  },
  {
    code: "ADMIN",
    description: "Perfil administrativo com operacao ampla na empresa.",
    isAdministrator: true,
    isSystem: true,
    level: "ADMIN",
    name: "Administrador",
    sequenceNumber: 1,
    status: "ACTIVE",
    tier: "ADMINISTRATOR",
  },
  {
    code: "MANAGER",
    description: "Perfil de gestao com acesso operacional.",
    isAdministrator: false,
    isSystem: true,
    level: "MANAGER",
    name: "Gestor",
    sequenceNumber: 2,
    status: "ACTIVE",
    tier: "MANAGER",
  },
  {
    code: "ANALYST",
    description: "Perfil de operacao com acesso controlado.",
    isAdministrator: false,
    isSystem: true,
    level: "ANALYST",
    name: "Analista",
    sequenceNumber: 3,
    status: "ACTIVE",
    tier: "BASIC",
  },
] as const;

type PermissionSeed = {
  canCreate?: boolean;
  canDelete?: boolean;
  canEdit?: boolean;
  canManage?: boolean;
  canView?: boolean;
  resourceCode: ResourceCode;
};

export const accessProfilePermissionSeedMap: Record<
  (typeof accessProfileSeedCatalog)[number]["code"],
  PermissionSeed[]
> = {
  OWNER: [
    { resourceCode: RESOURCE_CODES.dashboard, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmCommercial, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmDashboard, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmCustomer, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmRelationship, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmProvidedServices, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmCommercialProposal, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmCustomerContracts, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.crmSalesRepresentative, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrative, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeDashboard, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplier, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplierContracts, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativePurchases, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplies, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeProjectsTasks, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeFinancialBudget, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.administrativeFinancialGoals, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.assetControl, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financial, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialDashboard, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialBankAccounts, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialCreditCard, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialChartOfAccounts, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialBilling, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialAccountsPayable, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialAccountsReceivable, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialTransactions, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialDocumentImport, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialReconciliation, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.financialStatements, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.humanResources, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.humanResourcesEmployees, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.humanResourcesManagement, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.reports, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.settings, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.subscriberCompany, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.accessManagement, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.userAccount, canView: true, canEdit: true, canCreate: true, canDelete: true },
    { resourceCode: RESOURCE_CODES.accessProfiles, canView: true, canEdit: true, canCreate: true, canDelete: true },
    { resourceCode: RESOURCE_CODES.accessProfileEditor, canView: true, canEdit: true, canCreate: true, canDelete: true },
    { resourceCode: RESOURCE_CODES.subscriptionManagement, canView: true, canEdit: true, canManage: true },
  ],
  ADMIN: [
    { resourceCode: RESOURCE_CODES.dashboard, canView: true, canEdit: true },
    {
      resourceCode: RESOURCE_CODES.crmCommercial,
      canView: true,
      canEdit: true,
      canCreate: true,
      canDelete: true,
    },
    { resourceCode: RESOURCE_CODES.crmDashboard, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.crmCustomer, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.crmRelationship, canView: true, canEdit: true },
    {
      resourceCode: RESOURCE_CODES.crmProvidedServices,
      canView: true,
      canEdit: true,
      canCreate: true,
      canDelete: true,
    },
    {
      resourceCode: RESOURCE_CODES.crmCommercialProposal,
      canView: true,
      canEdit: true,
      canCreate: true,
      canDelete: true,
    },
    { resourceCode: RESOURCE_CODES.crmCustomerContracts, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.crmSalesRepresentative, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrative, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeDashboard, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplier, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplierContracts, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativePurchases, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplies, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeProjectsTasks, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeFinancialBudget, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeFinancialGoals, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.assetControl, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financial, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialDashboard, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialBankAccounts, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialCreditCard, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialChartOfAccounts, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialBilling, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialAccountsPayable, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialAccountsReceivable, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialTransactions, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialDocumentImport, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialReconciliation, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financialStatements, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.humanResources, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.humanResourcesEmployees, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.humanResourcesManagement, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.reports, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.settings, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.subscriberCompany, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.accessManagement, canView: true, canEdit: true, canManage: true },
    { resourceCode: RESOURCE_CODES.userAccount, canView: true, canEdit: true, canCreate: true, canDelete: true },
    { resourceCode: RESOURCE_CODES.accessProfiles, canView: true, canEdit: true, canCreate: true, canDelete: true },
    { resourceCode: RESOURCE_CODES.accessProfileEditor, canView: true, canEdit: true, canCreate: true, canDelete: true },
    { resourceCode: RESOURCE_CODES.subscriptionManagement, canView: true, canEdit: true, canManage: true },
  ],
  MANAGER: [
    { resourceCode: RESOURCE_CODES.dashboard, canView: true },
    {
      resourceCode: RESOURCE_CODES.crmCommercial,
      canView: true,
      canEdit: true,
      canCreate: true,
    },
    { resourceCode: RESOURCE_CODES.crmDashboard, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.crmCustomer, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.crmRelationship, canView: true, canEdit: true },
    {
      resourceCode: RESOURCE_CODES.crmProvidedServices,
      canView: true,
      canEdit: true,
      canCreate: true,
    },
    {
      resourceCode: RESOURCE_CODES.crmCommercialProposal,
      canView: true,
      canEdit: true,
      canCreate: true,
    },
    { resourceCode: RESOURCE_CODES.crmCustomerContracts, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.crmSalesRepresentative, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrative, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeDashboard, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplier, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplierContracts, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativePurchases, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeSupplies, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeProjectsTasks, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeFinancialBudget, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.administrativeFinancialGoals, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.assetControl, canView: true, canEdit: true },
    { resourceCode: RESOURCE_CODES.financial, canView: true },
    { resourceCode: RESOURCE_CODES.financialDashboard, canView: true },
    { resourceCode: RESOURCE_CODES.financialBankAccounts, canView: true },
    { resourceCode: RESOURCE_CODES.financialCreditCard, canView: true },
    { resourceCode: RESOURCE_CODES.financialChartOfAccounts, canView: true },
    { resourceCode: RESOURCE_CODES.financialBilling, canView: true },
    { resourceCode: RESOURCE_CODES.financialAccountsPayable, canView: true },
    { resourceCode: RESOURCE_CODES.financialAccountsReceivable, canView: true },
    { resourceCode: RESOURCE_CODES.financialTransactions, canView: true },
    { resourceCode: RESOURCE_CODES.financialDocumentImport, canView: true },
    { resourceCode: RESOURCE_CODES.financialReconciliation, canView: true },
    { resourceCode: RESOURCE_CODES.financialStatements, canView: true },
    { resourceCode: RESOURCE_CODES.humanResources, canView: true },
    { resourceCode: RESOURCE_CODES.humanResourcesEmployees, canView: true },
    { resourceCode: RESOURCE_CODES.humanResourcesManagement, canView: true },
    { resourceCode: RESOURCE_CODES.reports, canView: true },
    { resourceCode: RESOURCE_CODES.accessManagement, canView: true },
    { resourceCode: RESOURCE_CODES.userAccount, canView: true, canEdit: true, canCreate: true, canDelete: true },
  ],
  ANALYST: [
    { resourceCode: RESOURCE_CODES.dashboard, canView: true },
    { resourceCode: RESOURCE_CODES.crmCommercial, canView: true },
    { resourceCode: RESOURCE_CODES.crmDashboard, canView: true },
    { resourceCode: RESOURCE_CODES.crmCustomer, canView: true },
    { resourceCode: RESOURCE_CODES.crmRelationship, canView: true },
    { resourceCode: RESOURCE_CODES.crmProvidedServices, canView: true },
    { resourceCode: RESOURCE_CODES.crmCommercialProposal, canView: true },
    { resourceCode: RESOURCE_CODES.crmCustomerContracts, canView: true },
    { resourceCode: RESOURCE_CODES.crmSalesRepresentative, canView: true },
    { resourceCode: RESOURCE_CODES.reports, canView: true },
  ],
};
