export const RESOURCE_CODES = {
  accessManagement: "access-management",
  accessProfileEditor: "access-profile-editor",
  accessProfiles: "access-profiles",
  administrative: "administrative",
  administrativeDashboard: "administrative-dashboard",
  administrativeFinancialBudget: "administrative-financial-budget",
  administrativeFinancialGoals: "administrative-financial-goals",
  administrativeProjectsTasks: "administrative-projects-tasks",
  administrativePurchases: "administrative-purchases",
  administrativeSupplier: "administrative-supplier",
  administrativeSupplierContracts: "administrative-supplier-contracts",
  administrativeSupplies: "administrative-supplies",
  assetControl: "asset-control",
  crmCommercialProposal: "crm-commercial-proposal",
  crmCommercial: "crm-commercial",
  crmCustomer: "crm-customer",
  crmCustomerContracts: "crm-customer-contracts",
  crmDashboard: "crm-dashboard",
  crmProvidedServices: "crm-provided-services",
  crmRelationship: "crm-relationship",
  crmSalesRepresentative: "crm-sales-representative",
  dashboard: "dashboard",
  financial: "financial",
  financialAccountsPayable: "financial-accounts-payable",
  financialAccountsReceivable: "financial-accounts-receivable",
  financialBankAccounts: "financial-bank-accounts",
  financialBilling: "financial-billing",
  financialChartOfAccounts: "financial-chart-of-accounts",
  financialCreditCard: "financial-credit-card",
  financialDashboard: "financial-dashboard",
  financialDocumentImport: "financial-document-import",
  financialReconciliation: "financial-reconciliation",
  financialStatements: "financial-statements",
  financialTransactions: "financial-transactions",
  humanResourcesEmployees: "human-resources-employees",
  humanResourcesManagement: "human-resources-management",
  humanResources: "human-resources",
  reports: "reports",
  settings: "settings",
  subscriberCompany: "subscriber-company",
  subscriptionManagement: "subscription-management",
  userAccount: "user-account",
} as const;

export type ResourceCode = (typeof RESOURCE_CODES)[keyof typeof RESOURCE_CODES];
export type PermissionAction = "view" | "edit" | "create" | "delete" | "manage";

export type PermissionGrant = {
  canCreate: boolean;
  canDelete: boolean;
  canEdit: boolean;
  canManage: boolean;
  canView: boolean;
  resourceCode: ResourceCode;
};

export type PermissionResourceCatalogItem = {
  area: string;
  code: ResourceCode;
  description: string;
  isMenuVisible: boolean;
  module: string;
  name: string;
  parentCode?: ResourceCode;
  route?: string;
  sortOrder: number;
};

export const permissionResourceCatalog: PermissionResourceCatalogItem[] = [
  {
    area: "workspace",
    code: RESOURCE_CODES.dashboard,
    description: "Acesso ao painel executivo principal do sistema.",
    isMenuVisible: true,
    module: "Dashboard",
    name: "Dashboard Executivo",
    route: "/",
    sortOrder: 10,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmCommercial,
    description: "Visibilidade da estrutura CRM e Comercial.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "CRM / Comercial",
    route: "/crm/painel",
    sortOrder: 20,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmDashboard,
    description: "Acesso ao painel principal do modulo CRM e Comercial.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Painel CRM",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/crm/painel",
    sortOrder: 21,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmCustomer,
    description: "Acesso ao cadastro e acompanhamento de clientes.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Cliente",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/crm/cliente",
    sortOrder: 22,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmRelationship,
    description: "Acesso ao fluxo de relacionamento comercial.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Relacionamento",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/crm/relacionamento",
    sortOrder: 23,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmProvidedServices,
    description: "Acesso ao controle de servicos prestados.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Servicos Prestados",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/crm/servicos",
    sortOrder: 24,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmCommercialProposal,
    description: "Acesso a proposta comercial.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Proposta Comercial",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/comercial/proposta-comercial",
    sortOrder: 25,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmCustomerContracts,
    description: "Acesso aos contratos de clientes.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Contratos Clientes",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/comercial/contratos-clientes",
    sortOrder: 26,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.crmSalesRepresentative,
    description: "Acesso ao cadastro de representante comercial.",
    isMenuVisible: true,
    module: "CRM / Comercial",
    name: "Representante Comercial",
    parentCode: RESOURCE_CODES.crmCommercial,
    route: "/comercial/representante-comercial",
    sortOrder: 27,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrative,
    description: "Visibilidade da estrutura administrativa.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Administrativo",
    route: "/administrativo/painel",
    sortOrder: 30,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeDashboard,
    description: "Acesso ao painel principal do modulo administrativo.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Painel Administrativo",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/painel",
    sortOrder: 31,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeSupplier,
    description: "Acesso ao cadastro de fornecedores.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Fornecedor",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/fornecedor",
    sortOrder: 32,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeSupplierContracts,
    description: "Acesso aos contratos de fornecedores.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Contratos Fornecedores",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/contrato-de-fornecedor",
    sortOrder: 33,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativePurchases,
    description: "Acesso ao modulo de compras.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Compras",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/compras",
    sortOrder: 34,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeSupplies,
    description: "Acesso ao modulo de suprimentos.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Suprimentos",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/suprimentos",
    sortOrder: 35,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.assetControl,
    description: "Visibilidade da area de controle patrimonial.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Controle Patrimonial",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/controle-patrimonial",
    sortOrder: 36,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeProjectsTasks,
    description: "Acesso ao modulo de projetos e tarefas.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Projetos e Tarefas",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/projetos-e-tarefas",
    sortOrder: 37,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeFinancialBudget,
    description: "Acesso ao orcamento financeiro administrativo.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Orcamento Financeiro",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/orcamento-financeiro",
    sortOrder: 38,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.administrativeFinancialGoals,
    description: "Acesso ao modulo de metas financeiras.",
    isMenuVisible: true,
    module: "Administrativo",
    name: "Metas Financeiras",
    parentCode: RESOURCE_CODES.administrative,
    route: "/administrativo/metas-financeiras",
    sortOrder: 39,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financial,
    description: "Visibilidade da estrutura financeira.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Financeiro",
    route: "/financeiro/painel",
    sortOrder: 40,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialDashboard,
    description: "Acesso ao painel principal do modulo financeiro.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Painel Financeiro",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/painel",
    sortOrder: 41,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialBankAccounts,
    description: "Acesso a contas bancarias.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Contas Bancarias",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/contas-bancarias",
    sortOrder: 42,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialCreditCard,
    description: "Acesso ao cadastro de cartoes de credito.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Cartao de Credito",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/cartao-de-credito",
    sortOrder: 43,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialChartOfAccounts,
    description: "Acesso ao plano de contas.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Plano de Contas",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/plano-de-contas",
    sortOrder: 44,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialBilling,
    description: "Acesso ao fluxo de faturamento.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Faturamento",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/faturamento",
    sortOrder: 45,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialAccountsPayable,
    description: "Acesso a contas a pagar.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Contas a Pagar",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/contas-a-pagar",
    sortOrder: 46,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialAccountsReceivable,
    description: "Acesso a contas a receber.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Contas a Receber",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/contas-a-receber",
    sortOrder: 47,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialTransactions,
    description: "Acesso ao fluxo de transacoes.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Transacoes",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/transacoes",
    sortOrder: 48,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialDocumentImport,
    description: "Acesso a importacao de documentos.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Importar Documentos",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/importar-documentos",
    sortOrder: 49,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialReconciliation,
    description: "Acesso a conciliacao financeira.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Conciliacao",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/conciliacao",
    sortOrder: 50,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.financialStatements,
    description: "Acesso aos demonstrativos financeiros.",
    isMenuVisible: true,
    module: "Financeiro",
    name: "Demonstrativos",
    parentCode: RESOURCE_CODES.financial,
    route: "/financeiro/demonstrativos",
    sortOrder: 51,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.humanResources,
    description: "Visibilidade da estrutura de recursos humanos.",
    isMenuVisible: true,
    module: "Recursos Humanos",
    name: "Recursos Humanos",
    route: "/recursos-humanos/colaboradores",
    sortOrder: 50,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.humanResourcesEmployees,
    description: "Acesso ao cadastro de colaboradores.",
    isMenuVisible: true,
    module: "Recursos Humanos",
    name: "Colaboradores",
    parentCode: RESOURCE_CODES.humanResources,
    route: "/recursos-humanos/colaboradores",
    sortOrder: 52,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.humanResourcesManagement,
    description: "Acesso a gestao de RH.",
    isMenuVisible: true,
    module: "Recursos Humanos",
    name: "Gestao de RH",
    parentCode: RESOURCE_CODES.humanResources,
    route: "/recursos-humanos/gestao-de-rh",
    sortOrder: 53,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.reports,
    description: "Visibilidade da area de demonstrativos e relatorios.",
    isMenuVisible: true,
    module: "Demonstrativos e Relatorios",
    name: "Demonstrativos e Relatorios",
    route: "/demonstrativos-e-relatorios",
    sortOrder: 60,
  },
  {
    area: "modulos",
    code: RESOURCE_CODES.settings,
    description: "Visibilidade da area de configuracoes.",
    isMenuVisible: true,
    module: "Configuracoes",
    name: "Configuracoes",
    route: "/configuracoes",
    sortOrder: 70,
  },
  {
    area: "assinante",
    code: RESOURCE_CODES.subscriberCompany,
    description: "Acesso ao cadastro e manutencao da empresa assinante.",
    isMenuVisible: false,
    module: "Conta do Assinante",
    name: "Cadastro do Assinante",
    route: "/assinante",
    sortOrder: 80,
  },
  {
    area: "assinante",
    code: RESOURCE_CODES.accessManagement,
    description: "Acesso a gestao de usuarios da empresa ativa.",
    isMenuVisible: false,
    module: "Conta do Assinante",
    name: "Gestao de Acessos",
    parentCode: RESOURCE_CODES.subscriberCompany,
    route: "/assinante/gestao-acessos",
    sortOrder: 90,
  },
  {
    area: "assinante",
    code: RESOURCE_CODES.userAccount,
    description: "Acesso ao cadastro e manutencao da conta de usuario da empresa ativa.",
    isMenuVisible: false,
    module: "Conta do Assinante",
    name: "Conta do Usuario",
    parentCode: RESOURCE_CODES.accessManagement,
    route: "/assinante/gestao-acessos/usuarios/novo",
    sortOrder: 100,
  },
  {
    area: "assinante",
    code: RESOURCE_CODES.accessProfiles,
    description: "Acesso a listagem de perfis de acesso da empresa ativa.",
    isMenuVisible: false,
    module: "Conta do Assinante",
    name: "Lista de Perfis de Acesso",
    parentCode: RESOURCE_CODES.accessManagement,
    route: "/assinante/gestao-acessos/perfis",
    sortOrder: 110,
  },
  {
    area: "assinante",
    code: RESOURCE_CODES.accessProfileEditor,
    description: "Acesso ao cadastro e manutencao da matriz de permissoes de um perfil.",
    isMenuVisible: false,
    module: "Conta do Assinante",
    name: "Perfil de Acesso",
    parentCode: RESOURCE_CODES.accessProfiles,
    route: "/assinante/gestao-acessos/perfis/novo",
    sortOrder: 120,
  },
  {
    area: "assinante",
    code: RESOURCE_CODES.subscriptionManagement,
    description: "Acesso a gestao da assinatura da empresa ativa.",
    isMenuVisible: false,
    module: "Conta do Assinante",
    name: "Gestao da Assinatura",
    parentCode: RESOURCE_CODES.subscriberCompany,
    route: "/assinante/gestao-assinatura",
    sortOrder: 130,
  },
] as const;

export function hasPermission(
  permissions: PermissionGrant[],
  resourceCode: ResourceCode,
  action: PermissionAction = "view",
) {
  const permission = permissions.find((item) => item.resourceCode === resourceCode);

  if (!permission) {
    return false;
  }

  if (action === "manage") {
    return permission.canManage || permission.canDelete;
  }

  if (action === "delete") {
    return permission.canDelete || permission.canManage;
  }

  if (action === "create") {
    return permission.canCreate || permission.canDelete || permission.canManage;
  }

  if (action === "edit") {
    return (
      permission.canEdit ||
      permission.canCreate ||
      permission.canDelete ||
      permission.canManage
    );
  }

  return (
    permission.canView ||
    permission.canEdit ||
    permission.canCreate ||
    permission.canDelete ||
    permission.canManage
  );
}
